name = "ssl-checker"
main = "cloudflare-worker-ssl-checker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "ssl-checker"

[observability.logs]
enabled = true

routes = [
  { pattern = "ssl-checker.russ.tools", custom_domain = true }
]