// Generates the barrel entry design-sync bundles from.
//
// This repo is an Astro app, not a published component package: there is no
// dist/ library build and no shipped .d.ts, so the converter has nothing to
// resolve as an entry. Rather than hand-maintain a barrel (which silently
// rots when a component is added to src/components/ui/), this regenerates it
// from the directory listing on every sync.
//
// `export *` per file means every compound sub-part (CardHeader, SelectItem,
// DialogFooter, …) lands on window.RussTools alongside the 23 primaries, so
// designs can compose the real API even though only the primaries get cards.

import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';

const DIR = 'src/components/ui';
const OUT = '.design-sync/.cache/entry.jsx';

const files = readdirSync(DIR).filter((f) => f.endsWith('.jsx')).sort();
if (!files.length) throw new Error(`no components in ${DIR}`);

mkdirSync('.design-sync/.cache', { recursive: true });
writeFileSync(
  OUT,
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit.\n' +
    files.map((f) => `export * from '../../${DIR}/${f}';`).join('\n') +
    '\n',
);

console.error(`gen-entry: ${files.length} files -> ${OUT}`);
