name = "microsoft-tenant-lookup"
main = "../tenant.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "tenant.russ.tools", custom_domain = true }
]

# Use: npx wrangler secret put GRAPH_CLIENT_ID --config cloudflare-worker/configs/wrangler-tenant.toml
# Use: npx wrangler secret put GRAPH_CLIENT_SECRET --config cloudflare-worker/configs/wrangler-tenant.toml 
# Use: npx wrangler secret put GRAPH_TENANT_ID --config cloudflare-worker/configs/wrangler-tenant.toml
# Use: npx wrangler secret put ALLOWED_ORIGINS --config cloudflare-worker/configs/wrangler-tenant.toml 