name = "ssl-checker"
main = "../ssl.js"
compatibility_date = "2023-12-01"

routes = [
  { pattern = "ssl.russ.tools", custom_domain = true }
]

# Use: npx wrangler secret put ALLOWED_ORIGINS --config cloudflare-worker/configs/wrangler-ssl.toml