name = "buzzword-generator"
main = "../buzzwords.js"
compatibility_date = "2025-05-05"

routes = [
  { pattern = "buzzwords.russ.tools", custom_domain = true }
]

# Rate limiting using Cloudflare's Rate Limiting API (simplified approach)
[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

# Rate limiting: 100 requests per 60 seconds per IP/pathname
# Following the official Cloudflare documentation example