name = "certificate-chain-russ-tools"
main = "../certificate-chain.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Enable TCP sockets for TLS connections
[unsafe]
bindings = [
  { name = "SOCKET", type = "socket" }
]

[vars]
ENVIRONMENT = "development"
DEBUG_MODE = "true"
CACHE_TTL = "1800"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer/1.0"

[env.development]
name = "certificate-chain-russ-tools-dev"

[env.development.vars]
ENVIRONMENT = "development"
DEBUG_MODE = "true"
CACHE_TTL = "1800"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer/1.0"

[env.production]
name = "certificate-chain-russ-tools-prod"
route = { pattern = "certificate.russ.tools/*", zone_name = "russ.tools" }

[env.production.vars]
ENVIRONMENT = "production"
DEBUG_MODE = "false"
CACHE_TTL = "3600"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer/1.0"

# Secrets to be set via wrangler secret put:
# ALLOWED_ORIGINS - Comma-separated list of allowed CORS origins
# Example: wrangler secret put ALLOWED_ORIGINS --config configs/wrangler-certificate.toml --env production