name = "whois-lookup"
main = "../whois.js"
compatibility_date = "2023-12-01"

routes = [
  { pattern = "whois.russ.tools", custom_domain = true }
]

# Use: npx wrangler secret put ALLOWED_ORIGINS --config cloudflare-worker/configs/wrangler-whois.toml