name = "buzzword-generator"
main = "../buzzwords.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "buzzwords.russ.tools", custom_domain = true }
]

# Skip rate limiting for now - use Cloudflare's zone-level protection