name = "certificate-chain-russ-tools-python"
main = "../certificate-chain.py"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"
DEBUG_MODE = "true"
CACHE_TTL = "1800"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer Python/1.0"

[env.development]
name = "certificate-chain-russ-tools-python-dev"

[env.development.vars]
ENVIRONMENT = "development"
DEBUG_MODE = "true"
CACHE_TTL = "1800"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer Python/1.0"

[env.production]
name = "certificate-chain-russ-tools-python-prod"
route = { pattern = "certificate-python.russ.tools/*", zone_name = "russ.tools" }

[env.production.vars]
ENVIRONMENT = "production"
DEBUG_MODE = "false"
CACHE_TTL = "3600"
TIMEOUT = "30000"
MAX_REDIRECTS = "5"
USER_AGENT = "RussTools Certificate Analyzer Python/1.0"

# Secrets to be set via wrangler secret put:
# ALLOWED_ORIGINS - Comma-separated list of allowed CORS origins
# Example: wrangler secret put ALLOWED_ORIGINS --config configs/wrangler-certificate-python.toml --env production