name = "buzzword-generator"
main = "../buzzwords.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "buzzwords.russ.tools", custom_domain = true }
]

# Rate limiting bindings using Cloudflare's Rate Limiting API
[[unsafe.bindings]]
name = "RATE_LIMITER_MINUTE"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_HOUR"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 500, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_BURST"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 10, period = 10 }

# Rate limiting implemented using Cloudflare's Rate Limiting API
# - RATE_LIMITER_BURST: 10 requests per 10 seconds (anti-spam)
# - RATE_LIMITER_MINUTE: 60 requests per minute (normal usage)
# - RATE_LIMITER_HOUR: 500 requests per hour (daily usage tracking)