/**
 * The share-URL codec — **frozen contract #2**, ported byte-for-byte from
 * `src/utils/sharelink.js`.
 *
 * The wire format is:
 *
 *     safeStringify -> pako.deflate (raw zlib, NOT gzip) -> URL-safe base64
 *
 * plus a legacy branch that reads the uncompressed `btoa(JSON)` format some
 * links in the wild still use. Every one of those details is load-bearing:
 *
 *  - **zlib, not gzip.** `pako.deflate` emits a zlib wrapper (`0x78 …`).
 *    `pako.gzip` would be the obvious "modernisation" and would silently
 *    break every link ever shared.
 *  - **Padding is stripped** on encode and reconstructed on decode from
 *    `length % 4`. A decoder that requires padding rejects every existing URL.
 *  - **`safeStringify` drops values**, and that is part of the format: any
 *    object whose constructor is not `Object` or `Array` — a Date, a Map, a
 *    class instance — is encoded as `undefined` and therefore omitted, and a
 *    repeated object reference becomes the string `'[Circular]'` even when
 *    the graph is a DAG rather than a cycle. Tools have been written against
 *    that behaviour for years. It is pinned by tests, not fixed here.
 *
 * The only changes from the original are structural: the internals are
 * exported so the quirks above can be asserted directly, and `console.log`
 * on the legacy path is gone. No byte of output moves.
 *
 * The golden fixtures in `sharelink.test.js` were generated by running the
 * original module under Node and must keep decoding forever.
 */
import * as pako from 'pako';

/**
 * JSON.stringify with the original's replacer, quirks included.
 *
 * @param {unknown} obj
 * @returns {string}
 */
export const safeStringify = (obj) => {
  const seen = new Set();
  return JSON.stringify(obj, (key, value) => {
    if (typeof value === 'object' && value !== null) {
      if (seen.has(value)) {
        return '[Circular]';
      }
      seen.add(value);
    }
    // Skip function values and complex objects
    if (
      typeof value === 'function' ||
      (typeof value === 'object' &&
        value !== null &&
        value.constructor &&
        value.constructor.name !== 'Object' &&
        value.constructor.name !== 'Array')
    ) {
      return undefined;
    }
    return value;
  });
};

/**
 * @param {Uint8Array} bytes
 * @returns {string} URL-safe base64, unpadded
 */
const uint8ArrayToBase64Url = (bytes) => {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
};

/**
 * @param {string} base64Url
 * @returns {Uint8Array}
 */
const base64UrlToUint8Array = (base64Url) => {
  // Add padding if needed
  const padding = base64Url.length % 4;
  const base64 =
    base64Url.replace(/-/g, '+').replace(/_/g, '/') +
    (padding === 2 ? '==' : padding === 3 ? '=' : '');

  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

/**
 * @param {unknown} config
 * @returns {string}
 */
export const compressConfig = (config) => {
  try {
    const jsonString = safeStringify(config);
    const compressed = pako.deflate(jsonString);
    return uint8ArrayToBase64Url(compressed);
  } catch (error) {
    console.error('Failed to compress config:', error);
    throw new Error('Compression failed');
  }
};

/**
 * @param {string} encodedData
 * @returns {unknown}
 */
export const decompressConfig = (encodedData) => {
  try {
    const bytes = base64UrlToUint8Array(encodedData);
    const decompressed = pako.inflate(bytes, { to: 'string' });
    return JSON.parse(decompressed);
  } catch (error) {
    console.error('Failed to decompress config:', error);
    throw new Error('Decompression failed');
  }
};

/**
 * Build a `?config=` URL. `baseUrl` defaults to the current page, which is
 * why this must not be called during SSR.
 *
 * @param {unknown} config
 * @param {string} [baseUrl]
 * @returns {string|null} null if encoding failed
 */
export const generateShareableURL = (config, baseUrl) => {
  try {
    const encodedConfig = compressConfig(config);
    const currentUrl = baseUrl || window.location.origin + window.location.pathname;
    return `${currentUrl}?config=${encodedConfig}`;
  } catch (error) {
    console.error('Failed to generate shareable URL:', error);
    return null;
  }
};

/**
 * Read a config out of the query string, compressed or legacy.
 *
 * @param {URLSearchParams} searchParams
 * @returns {unknown|null}
 */
export const parseConfigFromURL = (searchParams) => {
  const configParam = searchParams.get('config');
  if (!configParam) {
    return null;
  }

  try {
    return decompressConfig(configParam);
  } catch {
    // Legacy format: uncompressed base64. Still in the wild, still supported.
    try {
      return JSON.parse(atob(configParam));
    } catch (legacyError) {
      console.error('Failed to parse legacy config format:', legacyError);
      return null;
    }
  }
};

/**
 * Write the config into the query string via whatever setter the caller has
 * — react-router's `setSearchParams` today, `history.replaceState` after the
 * ports. On failure the URL is deliberately left alone: a half-written
 * `?config=` is worse than a stale one.
 *
 * @param {unknown} config
 * @param {(params: Record<string,string>, options?: unknown) => void} setSearchParams
 * @param {unknown} [options]
 */
export const updateURLWithConfig = (config, setSearchParams, options = { replace: true }) => {
  try {
    const encodedConfig = compressConfig(config);
    setSearchParams({ config: encodedConfig }, options);
  } catch (error) {
    console.error('Failed to update URL:', error);
  }
};
