import { describe, it, expect, vi } from 'vitest';
import {
  safeStringify,
  compressConfig,
  generateShareableURL,
  parseConfigFromURL,
  updateURLWithConfig,
} from './sharelink.js';

/**
 * Frozen contract #2, tested against the port rather than the original.
 *
 * The golden fixtures below were generated by the **old** `sharelink.js`
 * running under Node, and encoded strings of exactly this shape exist in
 * links people have already shared. If the port had drifted by one byte —
 * gzip instead of zlib, padding retained, a different replacer — these would
 * fail, which is the whole point of committing them.
 */

const roundTrip = (config) => {
  const url = generateShareableURL(config, 'https://russ.tools/t');
  const encoded = url.split('?config=')[1];
  return parseConfigFromURL(new URLSearchParams(`config=${encoded}`));
};

describe('sharelink codec (core port)', () => {
  it('round-trips a simple config', () => {
    const config = { service: 'ssl', template: 'basic', parameters: { domain: 'example.com' } };
    expect(roundTrip(config)).toEqual(config);
  });

  it('round-trips nested arrays/objects (network-designer shape)', () => {
    const config = {
      networks: [
        {
          id: 'a',
          name: 'prod',
          cidr: '10.0.0.0/16',
          color: '#e74c3c',
          subnets: [{ name: 'web', size: 24 }],
        },
      ],
      selectedNetworkId: 'a',
    };
    expect(roundTrip(config)).toEqual(config);
  });

  it('round-trips unicode payloads', () => {
    const config = { note: 'café — ünïcode ☕', tags: ['a', 'b'] };
    expect(roundTrip(config)).toEqual(config);
  });

  it('builds a ?config= URL on the provided base', () => {
    const url = generateShareableURL({ a: 1 }, 'https://russ.tools/tool');
    expect(url).toMatch(/^https:\/\/russ\.tools\/tool\?config=[A-Za-z0-9_-]+$/);
  });

  it('returns null when no config param is present', () => {
    expect(parseConfigFromURL(new URLSearchParams(''))).toBeNull();
  });

  it('returns null (does not throw) on malformed input', () => {
    const error = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(parseConfigFromURL(new URLSearchParams('config=!!!not-base64!!!'))).toBeNull();
    error.mockRestore();
  });

  it('decodes the legacy uncompressed-base64 format', () => {
    const error = vi.spyOn(console, 'error').mockImplementation(() => {});
    // btoa(JSON.stringify({ service: 'legacy', parameters: { x: 1 } }))
    const legacyParam = 'eyJzZXJ2aWNlIjoibGVnYWN5IiwicGFyYW1ldGVycyI6eyJ4IjoxfX0=';
    expect(parseConfigFromURL(new URLSearchParams(`config=${legacyParam}`))).toEqual({
      service: 'legacy',
      parameters: { x: 1 },
    });
    error.mockRestore();
  });

  describe('the wire format itself', () => {
    it('is raw zlib, not gzip', () => {
      // zlib framing starts 0x78; gzip would start 0x1f 0x8b.
      const encoded = compressConfig({ a: 1 });
      const padding = encoded.length % 4;
      const bytes = atob(
        encoded.replace(/-/g, '+').replace(/_/g, '/') +
          (padding === 2 ? '==' : padding === 3 ? '=' : '')
      );
      expect(bytes.charCodeAt(0)).toBe(0x78);
    });

    it('emits URL-safe base64 with no padding', () => {
      const encoded = compressConfig({ domain: 'example.com', records: ['A', 'AAAA'] });
      expect(encoded).not.toMatch(/[+/=]/);
    });
  });

  describe("safeStringify's quirks are part of the format", () => {
    it('drops values whose constructor is neither Object nor Array', () => {
      class Subnet {
        constructor() {
          this.cidr = 24;
        }
      }
      // A class instance is silently omitted, not serialised.
      expect(safeStringify({ net: new Subnet(), name: 'x' })).toBe('{"name":"x"}');
      expect(safeStringify({ seen: new Map([['a', 1]]), name: 'x' })).toBe('{"name":"x"}');
    });

    it('but a Date survives as an ISO string, because toJSON runs first', () => {
      // Worth pinning explicitly: `JSON.stringify` calls `toJSON()` before
      // the replacer sees the value, so the constructor check never applies
      // to a Date. A "cleanup" that converts dates by hand would change the
      // encoded bytes of every link that carries one.
      expect(safeStringify({ when: new Date(0) })).toBe('{"when":"1970-01-01T00:00:00.000Z"}');
    });

    it("replaces a repeated reference with '[Circular]', DAG or not", () => {
      const shared = { n: 1 };
      expect(safeStringify({ a: shared, b: shared })).toBe('{"a":{"n":1},"b":"[Circular]"}');
    });

    it('drops functions', () => {
      expect(safeStringify({ fn: () => {}, keep: true })).toBe('{"keep":true}');
    });
  });

  describe('updateURLWithConfig', () => {
    it('hands the encoded config to the caller-supplied setter', () => {
      const setSearchParams = vi.fn();
      updateURLWithConfig({ a: 1 }, setSearchParams);

      expect(setSearchParams).toHaveBeenCalledTimes(1);
      const [params, options] = setSearchParams.mock.calls[0];
      expect(params.config).toMatch(/^[A-Za-z0-9_-]+$/);
      expect(options).toEqual({ replace: true });
    });

    it('leaves the URL alone when encoding throws', () => {
      const error = vi.spyOn(console, 'error').mockImplementation(() => {});
      const setSearchParams = vi.fn();
      // safeStringify handles cycles, so force a real failure instead: a
      // BigInt is the one thing JSON.stringify throws on outright.
      updateURLWithConfig({ big: 1n }, setSearchParams);

      expect(setSearchParams).not.toHaveBeenCalled();
      error.mockRestore();
    });
  });

  // Generated from the v1 codec (2026-07). Links carrying these exist in the
  // wild and MUST keep decoding forever.
  describe('v1 golden fixtures keep decoding', () => {
    const goldens = [
      [
        'eJwVykEKwCAMRNG7zLr0AN4m1VkETBUjpSDeven2_b_gHI9mIsG94sCk9Srzh0tcc1CXIcbJ4UgLpZnoHZmvxMozN8PeH7ZIGbM',
        { service: 'ssl', template: 'basic', parameters: { domain: 'example.com' } },
      ],
      [
        'eJyrVspLLSnPL8ouVrKKrlbKTFGyUkpU0lHKS8xNBTILivJTgLzkzJQiIM_QQA8M9Q3NQIL5OfkgUeVUc5Nk42SgSHFpEtA0iElQA8pTk0ASmVVAjpFJbWxtLJCXmpOaXJKa4gex2RNiZy0AUo0qaw',
        {
          networks: [
            {
              id: 'a',
              name: 'prod',
              cidr: '10.0.0.0/16',
              color: '#e74c3c',
              subnets: [{ name: 'web', size: 24 }],
            },
          ],
          selectedNetworkId: 'a',
        },
      ],
      [
        'eJwVzLsNwzAMhOFdWDuN4cpdmgzgDQjpkAihHqCoCIjh3S219x3-kyr0Fxxop-e_KV5B0VmEFjLEImyTEqxn_T60CeqgwsoRBq20n2Qh4uD0ns91-wxnZyGn2RTJfQwevpXhpg3XdQOgyCjj',
        {
          service: 'AzureFirewall',
          template: 'network-rules',
          parameters: { timeRange: '24h', action: 'Allow', dedupe: true },
        },
      ],
      [
        'eJyrVsrLL0lVslJKTkw7vFLhUcMUhcN78g6vT85PSVV4NGOqko5SSWJ6sZJVtFIikJ2kFFsLACkpE-4',
        { note: 'café — ünïcode ☕', tags: ['a', 'b'] },
      ],
    ];

    it.each(goldens)('decodes fixture %#', (encoded, expected) => {
      expect(parseConfigFromURL(new URLSearchParams(`config=${encoded}`))).toEqual(expected);
    });
  });

  it('re-encodes each golden fixture byte-for-byte', () => {
    // The stronger claim: not just "still decodes" but "still produces the
    // same bytes", which is what makes a shared link stable over time.
    const config = { service: 'ssl', template: 'basic', parameters: { domain: 'example.com' } };
    expect(compressConfig(config)).toBe(
      'eJwVykEKwCAMRNG7zLr0AN4m1VkETBUjpSDeven2_b_gHI9mIsG94sCk9Srzh0tcc1CXIcbJ4UgLpZnoHZmvxMozN8PeH7ZIGbM'
    );
  });
});
