#!/usr/bin/env node

/**
 * The tool inventory in the READMEs, generated from the manifests.
 *
 * Hand-maintained lists are why the docs claimed 11 tools in one place, 14 in
 * another and 15 in a third, and why they went on advertising the Network
 * Designer for a month after it was retired. The registry is the only thing
 * that knows what exists, so the tables are written from it.
 *
 * Each target file marks its table with a pair of comments and this replaces
 * what is between them:
 *
 *   <!-- TOOLS:START --> … <!-- TOOLS:END -->
 *
 * Run `pnpm generate:docs`. `docs.test.js` fails if a committed table has
 * drifted from the registry, so a tool added without regenerating is caught
 * in CI rather than noticed a year later.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { loadManifests } from '../src/tools/loadManifests.mjs';
import { CATEGORIES, categoryLabel } from '../src/shell/categories.mjs';

const START = '<!-- TOOLS:START -->';
const END = '<!-- TOOLS:END -->';

const tools = (await loadManifests()).sort(
  (a, b) =>
    CATEGORIES.findIndex((c) => c.id === a.category) -
      CATEGORIES.findIndex((c) => c.id === b.category) || a.title.localeCompare(b.title)
);

/**
 * Per-tool docs live at docs/tools/<id>/, but only where someone has written
 * them. A link to a directory that does not exist is worse than no link.
 * @param {string} id
 * @param {string} prefix  path from the file being written to docs/
 */
const docsLink = (id, prefix) =>
  existsSync(`docs/tools/${id}`) ? `[Docs](${prefix}tools/${id}/)` : '—';

/** @param {string} prefix */
export function toolTable(prefix) {
  const rows = tools.map(
    (t) =>
      `| **${t.title}** | ${categoryLabel(t.category)} | ${t.shortDescription} | \`${t.path}\` | ${docsLink(t.id, prefix)} |`
  );

  return [
    `<!-- Generated by scripts/generate-docs.mjs — run \`pnpm generate:docs\`. Do not edit by hand. -->`,
    '',
    `| Tool | Category | What it does | Path | Docs |`,
    `|---|---|---|---|---|`,
    ...rows,
    '',
    `${tools.length} tools.`,
  ].join('\n');
}

/** @param {string} file @param {string} prefix */
function rewrite(file, prefix) {
  const src = readFileSync(file, 'utf8');
  const start = src.indexOf(START);
  const end = src.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(`${file}: missing ${START} / ${END} markers`);
  }

  const next = `${src.slice(0, start + START.length)}\n${toolTable(prefix)}\n${src.slice(end)}`;
  if (next === src) return false;
  writeFileSync(file, next);
  return true;
}

// Only run the rewrite when invoked directly — the test imports toolTable().
if (import.meta.url === `file://${process.argv[1]}`) {
  const targets = [
    ['README.md', 'docs/'],
    ['docs/README.md', ''],
  ];
  for (const [file, prefix] of targets) {
    const changed = rewrite(file, prefix);
    console.log(`${changed ? '✅ updated' : '· unchanged'}  ${file}`);
  }
}
